"""Pydantic models for Module 1 — Startup Ingestion & Profiling.

FoundationIQ 3.0 (Startup Edition)
Accepts an 8-field onboarding form + up to 3 CSV uploads:
  - org_chart.csv     (roles, salaries, headcount)
  - expenses.csv      (monthly software / operational costs)
  - sales_inquiries.csv (inquiry date, payment date, repeat-customer tags)
"""

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Startup onboarding profile (replaces old CompanyMetadata)
# ---------------------------------------------------------------------------

class StartupProfile(BaseModel):
    """8-question onboarding form answers for a tech startup."""

    company_name: str = Field(..., examples=["Acme SaaS"])
    sub_type: Literal["EdTech", "FinTech", "SaaS", "E-commerce"] = Field(
        ..., description="Startup vertical"
    )
    mrr_last_3_months: list[float] = Field(
        ...,
        min_length=3,
        max_length=3,
        description="Monthly recurring revenue for past 3 months (₹), newest last",
        examples=[[80000, 95000, 110000]],
    )
    monthly_growth_goal_pct: float = Field(
        ..., ge=0, le=500,
        description="Target month-on-month growth percentage",
        examples=[15.0],
    )
    patience_months: int = Field(
        ..., ge=1, le=60,
        description="How many months the founder is willing to wait for ROI",
        examples=[6],
    )
    current_tech_stack: list[str] = Field(
        default_factory=list,
        description="Tools / platforms currently in use",
        examples=[["Stripe", "Zapier", "Google Sheets", "Freshdesk"]],
    )
    num_employees: int = Field(..., ge=1, examples=[12])
    industry: str = Field(
        default="Technology",
        description="High-level industry label (defaults to Technology)",
    )


# Legacy alias so downstream modules that import CompanyMetadata still work
# until they are migrated.  StartupProfile is a superset.
CompanyMetadata = StartupProfile


# ---------------------------------------------------------------------------
# Column summary (raw, untouched)
# ---------------------------------------------------------------------------

class ColumnInfo(BaseModel):
    """Summary of a single raw DataFrame column."""

    name: str
    dtype: str
    non_null_count: int
    null_count: int
    missing_pct: float = Field(..., description="Percentage of missing values (0-100)")


# ---------------------------------------------------------------------------
# Data issue flags
# ---------------------------------------------------------------------------

class IssueType(str, Enum):
    MISSING_VALUES = "missing_values"
    DUPLICATE_ROWS = "duplicate_rows"
    INCONSISTENT_COLUMN_NAMES = "inconsistent_column_names"
    UNPARSED_DATES = "unparsed_dates"
    MIXED_DTYPES = "mixed_dtypes"
    WHITESPACE_IN_STRINGS = "whitespace_in_strings"
    MISSING_EXPECTED_COLUMNS = "missing_expected_columns"


class DataIssue(BaseModel):
    """A single detected data quality problem — nothing is changed, only flagged."""

    issue_type: IssueType
    column: str | None = Field(None, description="Affected column, if column-specific")
    description: str
    affected_count: int | None = Field(None, description="Number of affected rows or cells")
    severity: Literal["low", "medium", "high"]


# ---------------------------------------------------------------------------
# Workflow analysis (from LLM) — kept for backward compat; Module 3 uses it
# ---------------------------------------------------------------------------

class WorkflowStep(BaseModel):
    """A single step extracted from the workflow description."""

    step_number: int
    description: str
    actor: str = Field(..., description="The role or person responsible for this step")
    step_type: Literal["Manual", "Automated", "Decision", "Unknown"]
    tool_used: str | None = None


class WorkflowDiagram(BaseModel):
    """Structured workflow output generated by the LLM."""

    steps: list[WorkflowStep]
    mermaid_diagram: str = Field(
        ..., description="Mermaid flowchart markup — render directly on the frontend"
    )
    summary: str = Field(..., description="One-paragraph executive summary of the workflow")


# ---------------------------------------------------------------------------
# Per-file ingestion summary
# ---------------------------------------------------------------------------

class FileIngestionSummary(BaseModel):
    """Summary of one uploaded CSV file after ingestion."""

    filename: str
    row_count: int
    column_count: int
    columns: list[ColumnInfo]
    data_issues: list[DataIssue] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# Startup profile analysis (LLM-generated)
# ---------------------------------------------------------------------------

class StartupProfileAnalysis(BaseModel):
    """LLM-generated analysis of the startup's current state."""

    mrr_trend: Literal["Growing", "Flat", "Declining"]
    mrr_mom_growth_pct: float = Field(
        ..., description="Average month-on-month MRR growth %"
    )
    growth_gap: str = Field(
        ..., description="Comparison of actual vs target growth"
    )
    tech_stack_maturity: Literal["Early", "Developing", "Mature"]
    key_observations: list[str] = Field(
        ..., description="3-5 bullet-point observations about the startup"
    )
    recommended_focus_areas: list[str] = Field(
        ..., description="Top 2-3 areas to investigate in subsequent modules"
    )
    executive_summary: str = Field(
        ..., description="One-paragraph executive summary of the startup profile"
    )


# ---------------------------------------------------------------------------
# API response
# ---------------------------------------------------------------------------

class IngestionResponse(BaseModel):
    """Response returned after a successful startup ingestion run."""

    session_id: str = Field(
        ..., description="Pass this to all subsequent module endpoints."
    )
    startup_profile: StartupProfile
    profile_analysis: StartupProfileAnalysis | None = Field(
        None, description="LLM-generated startup profile analysis"
    )
    # Per-file summaries (None if file not uploaded)
    org_chart: FileIngestionSummary | None = None
    expenses: FileIngestionSummary | None = None
    sales_inquiries: FileIngestionSummary | None = None
    # Aggregate stats
    files_uploaded: list[str] = Field(
        default_factory=list,
        description="Which CSV files were uploaded: org_chart, expenses, sales_inquiries",
    )
    total_issues: int = Field(0, description="Total data issues across all files")
    total_rows: int = Field(0, description="Total rows across all files")
