"""Pydantic models for the Data Ingestion module (Module 1)."""

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Company metadata
# ---------------------------------------------------------------------------

class CompanyMetadata(BaseModel):
    """Basic company profile supplied alongside the upload."""

    industry: str = Field(..., examples=["Retail"])
    num_employees: int = Field(..., ge=1, examples=[50])
    tools_used: list[str] = Field(
        default_factory=list,
        examples=[["Excel", "Google Sheets", "WhatsApp"]],
    )


# ---------------------------------------------------------------------------
# Column summary (raw, untouched)
# ---------------------------------------------------------------------------

class ColumnInfo(BaseModel):
    """Summary of a single raw DataFrame column."""

    name: str
    dtype: str
    non_null_count: int
    null_count: int
    missing_pct: float = Field(..., description="Percentage of missing values (0-100)")


# ---------------------------------------------------------------------------
# Data issue flags
# ---------------------------------------------------------------------------

class IssueType(str, Enum):
    MISSING_VALUES = "missing_values"
    DUPLICATE_ROWS = "duplicate_rows"
    INCONSISTENT_COLUMN_NAMES = "inconsistent_column_names"
    UNPARSED_DATES = "unparsed_dates"
    MIXED_DTYPES = "mixed_dtypes"
    WHITESPACE_IN_STRINGS = "whitespace_in_strings"


class DataIssue(BaseModel):
    """A single detected data quality problem — nothing is changed, only flagged."""

    issue_type: IssueType
    column: str | None = Field(None, description="Affected column, if column-specific")
    description: str
    affected_count: int | None = Field(None, description="Number of affected rows or cells")
    severity: Literal["low", "medium", "high"]


# ---------------------------------------------------------------------------
# Workflow analysis (from LLM)
# ---------------------------------------------------------------------------

class WorkflowStep(BaseModel):
    """A single step extracted from the workflow description."""

    step_number: int
    description: str
    actor: str = Field(..., description="The role or person responsible for this step")
    step_type: Literal["Manual", "Automated", "Decision", "Unknown"]
    tool_used: str | None = None


class WorkflowDiagram(BaseModel):
    """Structured workflow output generated by the LLM."""

    steps: list[WorkflowStep]
    mermaid_diagram: str = Field(
        ..., description="Mermaid flowchart markup — render directly on the frontend"
    )
    summary: str = Field(..., description="One-paragraph executive summary of the workflow")


# ---------------------------------------------------------------------------
# API response
# ---------------------------------------------------------------------------

class IngestionResponse(BaseModel):
    """Response returned after a successful ingestion run."""

    session_id: str = Field(
        ..., description="Pass this to all subsequent module endpoints."
    )
    # Raw data summary
    row_count: int
    column_count: int
    columns: list[ColumnInfo]
    # Detected issues (nothing was changed)
    data_issues: list[DataIssue] = Field(
        default_factory=list,
        description="Detected inconsistencies — all raw data is preserved as-is.",
    )
    # Workflow analysis
    workflow_text: str
    workflow_analysis: WorkflowDiagram | None = Field(
        None, description="Structured workflow + Mermaid diagram from LLM analysis"
    )
    company_metadata: CompanyMetadata
    # Document coverage
    documents_provided: list[str] = Field(
        default_factory=list,
        description="Which document types were uploaded: sales, invoices, payroll, inventory",
    )
